### ISSUE TITLE
Cache bust files on test run

### ISSUE THREAD

**Issue by phillipskevin** [bitovi/testee#60]
Files are not re-requested if they are cached by the browser (obviously).

The issue I ran into now is that if I enable coverage `testee test/qunit-tests.html --coverage` and then run again with it disabled `testee test/qunit-tests.html -c testee.json`, coverage data is still reported because the files were instrumented on the previous test run. This also happens the other way where coverage data does not show up because a previous run had coverage disabled. 

One solution is to do something similar to what Karma does and add a cache buster to the URL. If I remember correctly, Karma always adds a parameter like `?=234242411542` to each JS file requested.

**Comment by daffl** [comment]
We can't add parameters because that would mean rewriting every link that we find. Karma has more control over it because it runs it in its own environment. The best solution is probably to get https://github.com/ekryski/launchpad to handle profiles and create a new temporary one on every run (see https://github.com/ekryski/launchpad/issues/11).

**Comment by andrejewski** [comment]
Browser caching issues were addressed by #131. If these problems persist, this issue can be reopened.
